import { Font, StyleSheet } from "@react-pdf/renderer";

const COLORS = {
  pearl: "#F7FBFA",
  pearlDeep: "#EEF7F5",
  teal: "#0EA5A8",
  tealDark: "#0B7477",
  tealSoft: "#DFF6F4",
  navy: "#1F2937",
  slate: "#64748B",
  border: "#DCEBEA",
  borderStrong: "#B9DAD8",
  white: "#FFFFFF",
  mutedPanel: "#F9FCFB",
} as const;

const FONT = {
  regular: "Helvetica",
  bold: "Helvetica-Bold",
} as const;

const TYPOGRAPHY = {
  eyebrow: { fontFamily: FONT.bold, fontSize: 8.5, letterSpacing: 1.1, lineHeight: 1.25 },
  title: { fontFamily: FONT.bold, fontSize: 30, lineHeight: 1.12 },
  subtitle: { fontFamily: FONT.regular, fontSize: 11, lineHeight: 1.45 },
  sectionTitle: { fontFamily: FONT.bold, fontSize: 14, lineHeight: 1.25 },
  cardTitle: { fontFamily: FONT.bold, fontSize: 10.5, lineHeight: 1.3 },
  body: { fontFamily: FONT.regular, fontSize: 9.2, lineHeight: 1.45 },
  bodyBold: { fontFamily: FONT.bold, fontSize: 9.2, lineHeight: 1.45 },
  small: { fontFamily: FONT.regular, fontSize: 7.6, lineHeight: 1.35 },
  smallBold: { fontFamily: FONT.bold, fontSize: 7.6, lineHeight: 1.35 },
  footer: { fontFamily: FONT.bold, fontSize: 7.4, lineHeight: 1.25 },
} as const;

export const PAYMENT_TERMS = [
  "Pembayaran hanya mengikuti invoice resmi Sundaf Trip.",
  "DP mengunci seat dan nominalnya mengikuti invoice awal.",
  "Pelunasan wajib mengikuti jadwal settlement atau invoice terbaru.",
  "Add-on opsional, visa, dan layanan tambahan dibayar terpisah setelah dikonfirmasi.",
  "Bukti transfer wajib dikirim untuk verifikasi administrasi.",
  "Keterlambatan pembayaran dapat memengaruhi ketersediaan tiket, hotel, dan layanan.",
];
export const A4_PORTRAIT = { width: 595.28, height: 841.89 } as const;

Font.registerHyphenationCallback((word) => {
  if (word.length <= 24) return [word];
  return word.match(/.{1,14}/g) ?? [word];
});

export const s = StyleSheet.create({
  page: {
    backgroundColor: COLORS.pearl,
    color: COLORS.navy,
    fontFamily: FONT.regular,
    paddingTop: 74,
    paddingBottom: 56,
    paddingHorizontal: 38,
  },
  coverPage: {
    backgroundColor: COLORS.pearl,
    color: COLORS.navy,
    fontFamily: FONT.regular,
    paddingTop: 76,
    paddingBottom: 56,
    paddingHorizontal: 38,
  },
  header: {
    position: "absolute",
    top: 25,
    left: 38,
    right: 38,
    height: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 0.8,
    borderBottomColor: COLORS.border,
    paddingBottom: 9,
  },
  logo: {
    width: 102,
    height: 29,
    objectFit: "contain",
  },
  brandFallback: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  brandName: {
    fontFamily: FONT.bold,
    fontSize: 17,
    color: COLORS.tealDark,
    lineHeight: 1,
  },
  brandTrip: {
    fontFamily: FONT.bold,
    fontSize: 5.8,
    color: COLORS.navy,
    marginLeft: 2,
    marginTop: 1,
  },
  headerTitle: {
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    textAlign: "right",
    width: 260,
  },
  footer: {
    position: "absolute",
    left: 38,
    right: 38,
    bottom: 25,
    height: 22,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 0.8,
    borderTopColor: COLORS.border,
    paddingTop: 7,
  },
  footerLinks: {
    flexDirection: "row",
    width: 390,
  },
  footerLink: {
    ...TYPOGRAPHY.footer,
    color: COLORS.tealDark,
    textDecoration: "underline",
    marginRight: 20,
  },
  pageNumber: {
    position: "absolute",
    right: 38,
    bottom: 31,
    width: 55,
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    textAlign: "right",
  },
  coverIntro: {
    flexDirection: "row",
    marginTop: 3,
  },
  coverCopy: {
    width: 305,
    paddingRight: 18,
  },
  label: {
    ...TYPOGRAPHY.eyebrow,
    color: COLORS.tealDark,
    marginBottom: 8,
  },
  title: {
    ...TYPOGRAPHY.title,
    color: COLORS.navy,
    marginBottom: 9,
  },
  subtitle: {
    ...TYPOGRAPHY.subtitle,
    color: COLORS.slate,
  },
  heroWrap: {
    flex: 1,
    height: 220,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    padding: 5,
  },
  heroImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: 6,
  },
  heroFallback: {
    flex: 1,
    height: 220,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
  },
  heroFallbackText: {
    ...TYPOGRAPHY.cardTitle,
    color: COLORS.tealDark,
    textAlign: "center",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
    marginBottom: 4,
  },
  chip: {
    borderRadius: 10,
    backgroundColor: COLORS.tealSoft,
    borderWidth: 0.8,
    borderColor: COLORS.borderStrong,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginRight: 6,
    marginBottom: 6,
  },
  chipText: {
    ...TYPOGRAPHY.smallBold,
    color: COLORS.tealDark,
  },
  overviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 18,
  },
  overviewCard: {
    width: 249,
    minHeight: 72,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    padding: 12,
    marginRight: 10,
    marginBottom: 10,
  },
  overviewCardRight: {
    marginRight: 0,
  },
  overviewLabel: {
    ...TYPOGRAPHY.smallBold,
    color: COLORS.slate,
    marginBottom: 5,
  },
  overviewValue: {
    ...TYPOGRAPHY.cardTitle,
    color: COLORS.navy,
  },
  overviewPrice: {
    fontFamily: FONT.bold,
    fontSize: 13.5,
    lineHeight: 1.2,
    color: COLORS.tealDark,
  },
  priceSubline: {
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    marginTop: 3,
  },
  trustNote: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    padding: 13,
    marginTop: 4,
  },
  trustText: {
    ...TYPOGRAPHY.body,
    color: COLORS.slate,
  },
  sectionBlock: {
    marginBottom: 14,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionAccent: {
    width: 4,
    height: 18,
    borderRadius: 2,
    backgroundColor: COLORS.teal,
    marginRight: 8,
  },
  sectionTitle: {
    ...TYPOGRAPHY.sectionTitle,
    color: COLORS.navy,
  },
  sectionCard: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    padding: 14,
  },
  timeline: {
    marginTop: 2,
  },
  timelineItem: {
    flexDirection: "row",
    marginBottom: 11,
  },
  timelineRail: {
    width: 42,
    alignItems: "center",
  },
  timelineLine: {
    position: "absolute",
    top: 38,
    bottom: -11,
    left: 20,
    borderLeftWidth: 0.8,
    borderLeftColor: COLORS.borderStrong,
    borderStyle: "dashed",
  },
  dayBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    justifyContent: "center",
  },
  dayBadgeLabel: {
    fontFamily: FONT.bold,
    fontSize: 6.5,
    color: COLORS.white,
    lineHeight: 1,
  },
  dayBadgeNumber: {
    fontFamily: FONT.bold,
    fontSize: 13,
    color: COLORS.white,
    lineHeight: 1.05,
    marginTop: 1,
  },
  dayCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    padding: 12,
  },
  dayTitle: {
    ...TYPOGRAPHY.cardTitle,
    color: COLORS.navy,
    marginBottom: 5,
  },
  dayDescription: {
    ...TYPOGRAPHY.body,
    color: COLORS.navy,
    textAlign: "justify",
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  metaBadge: {
    backgroundColor: COLORS.tealSoft,
    borderRadius: 7,
    borderWidth: 0.7,
    borderColor: COLORS.borderStrong,
    paddingVertical: 4,
    paddingHorizontal: 7,
    marginRight: 6,
    marginBottom: 6,
  },
  metaLabel: {
    ...TYPOGRAPHY.smallBold,
    color: COLORS.tealDark,
  },
  metaValue: {
    ...TYPOGRAPHY.small,
    color: COLORS.navy,
    marginTop: 1,
  },
  noteText: {
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    marginTop: 6,
  },
  twoColumn: {
    flexDirection: "row",
  },
  columnLeft: {
    flex: 1,
    marginRight: 10,
  },
  columnRight: {
    flex: 1,
  },
  listTitle: {
    ...TYPOGRAPHY.cardTitle,
    color: COLORS.navy,
    marginBottom: 8,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  listIcon: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: COLORS.tealSoft,
    color: COLORS.tealDark,
    fontFamily: FONT.bold,
    fontSize: 8.5,
    lineHeight: 1.35,
    textAlign: "center",
    marginRight: 7,
    marginTop: 0.5,
  },
  listIconMuted: {
    backgroundColor: COLORS.pearlDeep,
    color: COLORS.slate,
  },
  listText: {
    flex: 1,
    ...TYPOGRAPHY.body,
    color: COLORS.navy,
  },
  addOnRow: {
    borderTopWidth: 0.7,
    borderTopColor: COLORS.border,
    paddingTop: 8,
    marginTop: 8,
  },
  addOnTop: {
    flexDirection: "row",
  },
  addOnName: {
    flex: 1,
    ...TYPOGRAPHY.bodyBold,
    color: COLORS.navy,
    paddingRight: 10,
  },
  addOnPrice: {
    width: 110,
    ...TYPOGRAPHY.bodyBold,
    color: COLORS.tealDark,
    textAlign: "right",
  },
  addOnDesc: {
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    marginTop: 3,
  },
  recommendedBadge: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.tealSoft,
    color: COLORS.tealDark,
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginTop: 5,
    ...TYPOGRAPHY.smallBold,
  },
  paymentIntro: {
    ...TYPOGRAPHY.body,
    color: COLORS.navy,
    marginBottom: 8,
  },
  paymentTable: {
    borderWidth: 0.8,
    borderColor: COLORS.border,
    borderRadius: 8,
    overflow: "hidden",
    marginTop: 6,
  },
  paymentRow: {
    flexDirection: "row",
    borderBottomWidth: 0.7,
    borderBottomColor: COLORS.border,
  },
  paymentHeader: {
    backgroundColor: COLORS.pearlDeep,
  },
  paymentCell: {
    paddingVertical: 7,
    paddingHorizontal: 8,
    ...TYPOGRAPHY.small,
    color: COLORS.navy,
  },
  paymentCellBold: {
    fontFamily: FONT.bold,
  },
  paymentStage: {
    width: 92,
  },
  paymentDue: {
    flex: 1,
  },
  paymentAmount: {
    width: 112,
    textAlign: "right",
  },
  termGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  termCard: {
    width: 249,
    backgroundColor: COLORS.mutedPanel,
    borderRadius: 8,
    borderWidth: 0.7,
    borderColor: COLORS.border,
    padding: 9,
    marginRight: 10,
    marginBottom: 8,
  },
  termCardRight: {
    marginRight: 0,
  },
  termText: {
    ...TYPOGRAPHY.small,
    color: COLORS.navy,
  },
  contactRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  contactLabel: {
    width: 76,
    ...TYPOGRAPHY.smallBold,
    color: COLORS.slate,
  },
  contactValue: {
    flex: 1,
    ...TYPOGRAPHY.body,
    color: COLORS.navy,
  },
  link: {
    color: COLORS.tealDark,
    fontFamily: FONT.bold,
    textDecoration: "underline",
  },
  profileText: {
    ...TYPOGRAPHY.body,
    color: COLORS.navy,
    textAlign: "justify",
  },
  galleryLeadRow: {
    flexDirection: "row",
    height: 286,
    marginTop: 2,
  },
  galleryLeadImage: {
    width: 333,
    height: 286,
    objectFit: "cover",
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
  },
  gallerySideStack: {
    flex: 1,
    marginLeft: 10,
  },
  gallerySideImage: {
    width: "100%",
    height: 138,
    objectFit: "cover",
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    marginBottom: 10,
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  galleryGridImage: {
    width: 249,
    height: 122,
    objectFit: "cover",
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: COLORS.border,
    marginRight: 10,
    marginBottom: 10,
  },
  galleryGridImageRight: {
    marginRight: 0,
  },
  galleryNote: {
    ...TYPOGRAPHY.small,
    color: COLORS.slate,
    marginTop: 4,
  },
});
