type QualityInput = {
  title: string;
  excerpt?: string | null;
  body: string;
  sourceContent?: string | null;
};

export type ContentQualityReport = {
  ok: boolean;
  issues: string[];
  wordCount: number;
};

export const MIN_SOURCE_CHARS = 350;

const FALSE_PERSONA_RE =
  /\b(saya|aku|gue|kami)\s+(pergi|berangkat|menginap|makan|naik|tiba|mengunjungi|melihat|ketemu|kehilangan|hampir|sempat|baru sadar|jalan)\b/i;

const AI_LEAK_RE = /\b(sebagai ai|chatgpt|openai|model bahasa|generated by ai|ai generated)\b/i;

const CLICHE_PATTERNS = [
  /\bperjalanan impian\b/i,
  /\btak terlupakan\b/i,
  /\bhidden gem\b/i,
  /\bwajib dikunjungi\b/i,
  /\bmenakjubkan\b/i,
  /\bmemukau\b/i,
  /\bmagis\b/i,
  /\binstagramable\b/i,
  /\bpesona\b/i,
  /\beksplorasi\b/i,
  /\bnikmati\b/i,
  /\bsempurna untuk\b/i,
  /\bmembuat siapa pun takjub\b/i,
];

function plainText(html: string) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

function wordCount(text: string) {
  return text.split(/\s+/).filter(Boolean).length;
}

export function hasUsableSource(sourceContent: string | null | undefined) {
  return typeof sourceContent === "string" && sourceContent.trim().length >= MIN_SOURCE_CHARS;
}

export function assessGeneratedContent(input: QualityInput): ContentQualityReport {
  const text = plainText(`${input.title}\n${input.excerpt ?? ""}\n${input.body}`);
  const count = wordCount(text);
  const issues: string[] = [];

  if (!hasUsableSource(input.sourceContent)) {
    issues.push("Sumber terlalu tipis untuk dibuat jadi artikel publik.");
  }

  if (count < 450) {
    issues.push("Draft terlalu pendek, tambahkan konteks yang bersumber atau tahan sebagai catatan internal.");
  }

  if (FALSE_PERSONA_RE.test(text)) {
    issues.push("Draft memakai first-person seolah Sundaf pernah mengalami sendiri. Ubah menjadi catatan editorial berbasis sumber.");
  }

  if (AI_LEAK_RE.test(text)) {
    issues.push("Draft masih membocorkan bahasa internal AI.");
  }

  if (text.includes("—")) {
    issues.push("Draft masih memakai em dash.");
  }

  const clicheCount = CLICHE_PATTERNS.filter((pattern) => pattern.test(text)).length;
  if (clicheCount >= 3) {
    issues.push("Draft masih terlalu banyak memakai klise travel generik.");
  }

  return { ok: issues.length === 0, issues, wordCount: count };
}

export function qualityErrorMessage(report: ContentQualityReport) {
  return `Draft ditahan quality gate: ${report.issues.join(" ")}`;
}
